n0=int(input('Digite um valor: '))
print(type(n0))
n1=float(input('Digite um valor: '))
print(n1)
n2=str(input('Digite um valor: '))
print(n2)
n3=bool(input('Digite um valor: '))
print(n3)
n4=bool(input('Digite um valor: '))
print(n4)
